#!/bin/bash

if [[ -f ~/.weechat/irc.conf ]]; then
        exec weechat
else
        exec weechat-curses -r "/server add newnet localhost -autoconnect; /set irc.server.newnet.autojoin \"#meta,#thunix,#tildetel\"; /connect newnet"
fi