#!/bin/bash
export RUNNING="/dev/shm/ansible_is_running"
export HOOK="/dev/shm/ansible-hook-last-run"

ansible_is_running()
{
	cd /var/thunix/ansible
	/usr/bin/git pull
	/usr/local/bin/ansible-playbook -i /var/thunix/ansible/hosts /var/thunix/ansible/site.yml -u root
}

if [ -f $RUNNING ]; then
   echo "Ansible is currently running."
else
	touch $RUNNING
	ansible_is_running
	touch $HOOK
	rm $RUNNING
fi
