---
- name: Setting up elevenkb
  user:
    name: elevenkb
    groups: tilde
    state: present
    skeleton: /etc/skel
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/elevenkb
- authorized_key:
    user: elevenkb
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHRwxMpLuryZbPTFt6pkhPplfbJPqxTqrx87Ds6ouSCR"
